./nom.sh ./raw/prenom/ccqueue.c-5-0-----1.log ./raw/ccqueue.c-5-0-----1.log
./nom.sh ./raw/prenom/ccqueue.c-5-0-----2.log ./raw/ccqueue.c-5-0-----2.log
./nom.sh ./raw/prenom/ccqueue.c-5-0-----3.log ./raw/ccqueue.c-5-0-----3.log
./nom.sh ./raw/prenom/ccqueue.c-5-0-----4.log ./raw/ccqueue.c-5-0-----4.log
./nom.sh ./raw/prenom/ccqueue.c-5-0-----5.log ./raw/ccqueue.c-5-0-----5.log
./nom.sh ./raw/prenom/ccqueue.c-p-0-----1.log ./raw/ccqueue.c-p-0-----1.log
./nom.sh ./raw/prenom/ccqueue.c-p-0-----2.log ./raw/ccqueue.c-p-0-----2.log
./nom.sh ./raw/prenom/ccqueue.c-p-0-----3.log ./raw/ccqueue.c-p-0-----3.log
./nom.sh ./raw/prenom/ccqueue.c-p-0-----4.log ./raw/ccqueue.c-p-0-----4.log
./nom.sh ./raw/prenom/ccqueue.c-p-0-----5.log ./raw/ccqueue.c-p-0-----5.log
./nom.sh ./raw/prenom/hlcrq.c-5-0-----1.log ./raw/hlcrq.c-5-0-----1.log
./nom.sh ./raw/prenom/hlcrq.c-5-0-----2.log ./raw/hlcrq.c-5-0-----2.log
./nom.sh ./raw/prenom/hlcrq.c-5-0-----3.log ./raw/hlcrq.c-5-0-----3.log
./nom.sh ./raw/prenom/hlcrq.c-5-0-----4.log ./raw/hlcrq.c-5-0-----4.log
./nom.sh ./raw/prenom/hlcrq.c-5-0-----5.log ./raw/hlcrq.c-5-0-----5.log
./nom.sh ./raw/prenom/hlcrq.c-p-0-----1.log ./raw/hlcrq.c-p-0-----1.log
./nom.sh ./raw/prenom/hlcrq.c-p-0-----2.log ./raw/hlcrq.c-p-0-----2.log
./nom.sh ./raw/prenom/hlcrq.c-p-0-----3.log ./raw/hlcrq.c-p-0-----3.log
./nom.sh ./raw/prenom/hlcrq.c-p-0-----4.log ./raw/hlcrq.c-p-0-----4.log
./nom.sh ./raw/prenom/hlcrq.c-p-0-----5.log ./raw/hlcrq.c-p-0-----5.log
./nom.sh ./raw/prenom/hqueue.c-5-0-----1.log ./raw/hqueue.c-5-0-----1.log
./nom.sh ./raw/prenom/hqueue.c-5-0-----2.log ./raw/hqueue.c-5-0-----2.log
./nom.sh ./raw/prenom/hqueue.c-5-0-----3.log ./raw/hqueue.c-5-0-----3.log
./nom.sh ./raw/prenom/hqueue.c-5-0-----4.log ./raw/hqueue.c-5-0-----4.log
./nom.sh ./raw/prenom/hqueue.c-5-0-----5.log ./raw/hqueue.c-5-0-----5.log
./nom.sh ./raw/prenom/hqueue.c-p-0-----1.log ./raw/hqueue.c-p-0-----1.log
./nom.sh ./raw/prenom/hqueue.c-p-0-----2.log ./raw/hqueue.c-p-0-----2.log
./nom.sh ./raw/prenom/hqueue.c-p-0-----3.log ./raw/hqueue.c-p-0-----3.log
./nom.sh ./raw/prenom/hqueue.c-p-0-----4.log ./raw/hqueue.c-p-0-----4.log
./nom.sh ./raw/prenom/hqueue.c-p-0-----5.log ./raw/hqueue.c-p-0-----5.log
./nom.sh ./raw/prenom/lcrq.c-5-0-----1.log ./raw/lcrq.c-5-0-----1.log
./nom.sh ./raw/prenom/lcrq.c-5-0-----2.log ./raw/lcrq.c-5-0-----2.log
./nom.sh ./raw/prenom/lcrq.c-5-0-----3.log ./raw/lcrq.c-5-0-----3.log
./nom.sh ./raw/prenom/lcrq.c-5-0-----4.log ./raw/lcrq.c-5-0-----4.log
./nom.sh ./raw/prenom/lcrq.c-5-0-----5.log ./raw/lcrq.c-5-0-----5.log
./nom.sh ./raw/prenom/lcrq.c-p-0-----1.log ./raw/lcrq.c-p-0-----1.log
./nom.sh ./raw/prenom/lcrq.c-p-0-----2.log ./raw/lcrq.c-p-0-----2.log
./nom.sh ./raw/prenom/lcrq.c-p-0-----3.log ./raw/lcrq.c-p-0-----3.log
./nom.sh ./raw/prenom/lcrq.c-p-0-----4.log ./raw/lcrq.c-p-0-----4.log
./nom.sh ./raw/prenom/lcrq.c-p-0-----5.log ./raw/lcrq.c-p-0-----5.log
./nom.sh ./raw/prenom/locksqueue.c-5-0-----1.log ./raw/locksqueue.c-5-0-----1.log
./nom.sh ./raw/prenom/locksqueue.c-5-0-----2.log ./raw/locksqueue.c-5-0-----2.log
./nom.sh ./raw/prenom/locksqueue.c-5-0-----3.log ./raw/locksqueue.c-5-0-----3.log
./nom.sh ./raw/prenom/locksqueue.c-5-0-----4.log ./raw/locksqueue.c-5-0-----4.log
./nom.sh ./raw/prenom/locksqueue.c-5-0-----5.log ./raw/locksqueue.c-5-0-----5.log
./nom.sh ./raw/prenom/locksqueue.c-p-0-----1.log ./raw/locksqueue.c-p-0-----1.log
./nom.sh ./raw/prenom/locksqueue.c-p-0-----2.log ./raw/locksqueue.c-p-0-----2.log
./nom.sh ./raw/prenom/locksqueue.c-p-0-----3.log ./raw/locksqueue.c-p-0-----3.log
./nom.sh ./raw/prenom/locksqueue.c-p-0-----4.log ./raw/locksqueue.c-p-0-----4.log
./nom.sh ./raw/prenom/locksqueue.c-p-0-----5.log ./raw/locksqueue.c-p-0-----5.log
./nom.sh ./raw/prenom/msqueue.c-5-0-1-22---1.log ./raw/msqueue.c-5-0-1-22---1.log
./nom.sh ./raw/prenom/msqueue.c-5-0-1-22---2.log ./raw/msqueue.c-5-0-1-22---2.log
./nom.sh ./raw/prenom/msqueue.c-5-0-1-22---3.log ./raw/msqueue.c-5-0-1-22---3.log
./nom.sh ./raw/prenom/msqueue.c-5-0-1-22---4.log ./raw/msqueue.c-5-0-1-22---4.log
./nom.sh ./raw/prenom/msqueue.c-5-0-1-22---5.log ./raw/msqueue.c-5-0-1-22---5.log
./nom.sh ./raw/prenom/msqueue.c-p-0-1-22---1.log ./raw/msqueue.c-p-0-1-22---1.log
./nom.sh ./raw/prenom/msqueue.c-p-0-1-22---2.log ./raw/msqueue.c-p-0-1-22---2.log
./nom.sh ./raw/prenom/msqueue.c-p-0-1-22---3.log ./raw/msqueue.c-p-0-1-22---3.log
./nom.sh ./raw/prenom/msqueue.c-p-0-1-22---4.log ./raw/msqueue.c-p-0-1-22---4.log
./nom.sh ./raw/prenom/msqueue.c-p-0-1-22---5.log ./raw/msqueue.c-p-0-1-22---5.log
./nom.sh ./raw/prenom/simqueue.c-5-0-23----1.log ./raw/simqueue.c-5-0-23----1.log
./nom.sh ./raw/prenom/simqueue.c-5-0-23----2.log ./raw/simqueue.c-5-0-23----2.log
./nom.sh ./raw/prenom/simqueue.c-5-0-23----3.log ./raw/simqueue.c-5-0-23----3.log
./nom.sh ./raw/prenom/simqueue.c-5-0-23----4.log ./raw/simqueue.c-5-0-23----4.log
./nom.sh ./raw/prenom/simqueue.c-5-0-23----5.log ./raw/simqueue.c-5-0-23----5.log
./nom.sh ./raw/prenom/simqueue.c-p-0-23----1.log ./raw/simqueue.c-p-0-23----1.log
./nom.sh ./raw/prenom/simqueue.c-p-0-23----2.log ./raw/simqueue.c-p-0-23----2.log
./nom.sh ./raw/prenom/simqueue.c-p-0-23----3.log ./raw/simqueue.c-p-0-23----3.log
./nom.sh ./raw/prenom/simqueue.c-p-0-23----4.log ./raw/simqueue.c-p-0-23----4.log
./nom.sh ./raw/prenom/simqueue.c-p-0-23----5.log ./raw/simqueue.c-p-0-23----5.log
